# Generated by Django 4.1.3 on 2022-11-08 20:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=tinymce.models.HTMLField(max_length=2000, verbose_name='Description'),
        ),
    ]
