# Generated by Django 4.1.3 on 2022-11-11 19:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('cover_image', models.ImageField(upload_to='media/news_cover_images', verbose_name='Cover Image')),
                ('des_image', models.ImageField(upload_to='media/news_des_images', verbose_name='Des Image')),
                ('description', tinymce.models.HTMLField(max_length=2000, verbose_name='Description')),
                ('slug', models.SlugField(editable=False, max_length=256, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
