# Generated by Django 4.1.3 on 2022-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='media/news_cover_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='des_image',
            field=models.ImageField(default=2, upload_to='media/news_des_images', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
