# Generated by Django 4.1.3 on 2022-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_description_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
    ]
