# Generated by Django 4.1.3 on 2022-11-08 20:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(max_length=2000, verbose_name='Description'),
        ),
    ]
