# Generated by Django 4.1.3 on 2022-11-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statitics',
            old_name='EUR',
            new_name='eur',
        ),
    ]
